# ==============================================================================
# File: config/outputs.conf
# Project: P2 — Windows Security Monitoring with Splunk
# Target Location: C:\Program Files\SplunkUniversalForwarder\etc\system\local\outputs.conf
# Description: Forwarding target configuration for Splunk Universal Forwarder on Windows 11.
#              Directs all ingested event streams to the central Splunk Enterprise receiver.
# ==============================================================================

[tcpout]
defaultGroup = splunk-enterprise

[tcpout:splunk-enterprise]
# Central Splunk Enterprise server receiving port (splunktcp://9997)
server = 192.168.100.7:9997
