# Splunk Universal Forwarder Inputs Configuration
# App Location: /opt/splunkforwarder/etc/apps/linux_security/local/inputs.conf
# Target Host: ubuntu-p3 (192.168.100.9)
# Destination Index: linux_security

[monitor:///var/log/auth.log]
disabled = false
index = linux_security
sourcetype = linux_secure
host = ubuntu-p3

[monitor:///var/log/syslog]
disabled = false
index = linux_security
sourcetype = syslog
host = ubuntu-p3

[monitor:///var/log/audit/audit.log]
disabled = false
index = linux_security
sourcetype = linux:audit
host = ubuntu-p3
